### ISSUE TITLE
Brainstorming Board for moving forward. 

### ISSUE THREAD

**Issue by BeatLink** [Librefox/Librefox#1]
Okay, so here we can start laying out the things we need to do to move forward with this fork. I'll just start with a few on the top of my head

* Rewrite the README to reflect the project's status as a completely independent non official fork that is neither endorsed by or related to Mozilla. 
* Find out how to compile Firefox with our own branding
* Replace all relevant references to Firefox with LibreVixen
* Determine a logo for the project. 
* Begin work on a full featured release.

**Comment by shreyasminocha** [comment]
I'll work on the readme.

**Comment by BeatLink** [comment]
Okay great! I've invited you to the new organization. We can continue this here https://github.com/librevixen/LibreVixen/issues/1
