### ISSUE TITLE
Rename the organization and repository to "LibreVixen"

### ISSUE THREAD

**Issue by BeatLink** [Librefox/Librefox#2]

**Comment by shreyasminocha** [comment]
I only have the right to rename the repository, not the organisation. That, AFAIK, no one but @intika can do.

**Comment by Serkan-devel** [comment]
Can it be renamed to something else?

**Comment by BeatLink** [comment]
> I only have the right to rename the repository, not the organisation. That, AFAIK, no one but @intika can do.

So we will _need_ to create a new organization. Remember, It could be the fox part of the name that started the gag order in the first place. I will go ahead and make it.

**Comment by BeatLink** [comment]
Here it is! https://github.com/librevixen. We should continue the work there.
